import { Database, MoreHorizontal, type LucideIcon } from 'lucide-react'
import type { DashboardActivity, DashboardStats } from './dashboard-types'

export function StatCard({ label, value, note, icon: Icon }: { label: string; value: string; note: string; icon: LucideIcon }) {
  return <div className="p-5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl transition hover:shadow-md"><div className="flex items-center justify-between text-sm text-slate-500 dark:text-slate-400 mb-2"><span>{label}</span><Icon size={16} /></div><strong className="text-2xl font-bold text-slate-900 dark:text-slate-100 block">{value}</strong><small className="text-xs text-slate-400 dark:text-slate-500 mt-1 block">{note}</small></div>
}

export function DashboardStatsGrid({ stats, icons }: { stats: DashboardStats; icons: { documents: LucideIcon; availableCopies: LucideIcon; activeLoans: LucideIcon; members: LucideIcon } }) {
  return <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4"><StatCard label="Documents catalogués" value={formatStat(stats.documents)} note={stats.documents === null ? 'Aucune donnée synchronisée' : 'Données synchronisées'} icon={icons.documents} /><StatCard label="Exemplaires disponibles" value={formatStat(stats.availableCopies)} note={stats.availableCopies === null ? 'Aucune donnée synchronisée' : 'Données synchronisées'} icon={icons.availableCopies} /><StatCard label="Emprunts actifs" value={formatStat(stats.activeLoans)} note={stats.activeLoans === null ? 'Aucune donnée synchronisée' : 'Données synchronisées'} icon={icons.activeLoans} /><StatCard label="Membres inscrits" value={formatStat(stats.members)} note={stats.members === null ? 'Aucune donnée synchronisée' : 'Données synchronisées'} icon={icons.members} /></div>
}

export function ActivityPanel({ activities }: { activities: DashboardActivity[] }) {
  return <section className="lg:col-span-2 p-6 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl"><div className="flex items-start justify-between mb-4"><div><h2 className="font-semibold">Activité récente</h2><p className="text-sm text-slate-500 dark:text-slate-400">Les dernières actions de votre espace.</p></div><button className="p-1 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 rounded" aria-label="Options"><MoreHorizontal size={18} /></button></div>{activities.length > 0 ? <div className="space-y-3">{activities.map((activity) => <div key={activity.id} className="flex items-center justify-between gap-4 border-b border-slate-100 dark:border-slate-800 pb-3 last:border-0 last:pb-0"><div className="min-w-0"><b className="block truncate text-sm text-slate-900 dark:text-slate-100">{activity.action}</b><span className="text-xs text-slate-500 dark:text-slate-400">{activity.entity || 'Bibliothèque'}</span></div><time className="shrink-0 text-xs text-slate-400 dark:text-slate-500">{formatActivityDate(activity.created_at)}</time></div>)}</div> : <div className="flex flex-col items-center justify-center py-12 text-center text-slate-500 dark:text-slate-400"><div className="w-12 h-12 bg-slate-100 dark:bg-slate-800 rounded-full flex items-center justify-center mb-3"><Database size={20} /></div><b className="text-slate-900 dark:text-slate-100">Aucune activité pour le moment</b><span className="text-sm mt-1">Les événements de votre bibliothèque apparaîtront ici.</span></div>}</section>
}

function formatStat(value: number | null) { return value === null ? '—' : value.toLocaleString('fr-FR') }
function formatActivityDate(value: string) { return new Intl.DateTimeFormat('fr-FR', { day: '2-digit', month: 'short' }).format(new Date(value)) }
