import Link from 'next/link'
import { ArrowLeft, Library } from 'lucide-react'

const content: Record<string, { title: string; eyebrow: string; paragraphs: string[] }> = {
  tarifs: { title: 'Des outils adaptés à votre bibliothèque', eyebrow: 'Tarifs', paragraphs: ['Biblius propose une plateforme modulaire pour les bibliothèques universitaires.', 'Contactez notre équipe pour définir l’accompagnement, les utilisateurs et les ressources nécessaires à votre établissement.'] },
  changelog: { title: 'Évolution de Biblius', eyebrow: 'Changelog', paragraphs: ['Biblius évolue avec les besoins des bibliothèques : catalogue, circulation, ressources numériques et intelligence documentaire.', 'Les nouvelles fonctionnalités sont déployées progressivement dans votre espace.'] },
  roadmap: { title: 'La suite de Biblius', eyebrow: 'Roadmap', paragraphs: ['Notre feuille de route couvre l’automatisation du catalogage, les recommandations et le pilotage des collections.', 'Les retours des bibliothécaires orientent les prochaines priorités.'] },
  documentation: { title: 'Documentation Biblius', eyebrow: 'Ressources', paragraphs: ['Retrouvez ici les informations nécessaires pour utiliser le catalogue, gérer les exemplaires, suivre les emprunts et exploiter les ressources numériques.', 'L’accès aux fonctions dépend du rôle attribué dans votre bibliothèque.'] },
  api: { title: 'API Biblius', eyebrow: 'Ressources', paragraphs: ['L’API Biblius permet d’intégrer le catalogue, les membres, les exemplaires et la circulation dans vos outils internes.', 'Les accès API doivent être protégés et configurés par un administrateur.'] },
  guides: { title: 'Guides pratiques', eyebrow: 'Ressources', paragraphs: ['Découvrez les bonnes pratiques pour structurer vos documents, associer les auteurs, appliquer Dewey et gérer les exemplaires.', 'Chaque guide accompagne les workflows disponibles dans le dashboard.'] },
  tutoriels: { title: 'Tutoriels Biblius', eyebrow: 'Ressources', paragraphs: ['Les tutoriels présentent les étapes essentielles pour administrer une bibliothèque universitaire avec Biblius.', 'Commencez par la configuration de votre catalogue et de vos rôles.'] },
  'a-propos': { title: 'À propos de Biblius', eyebrow: 'Entreprise', paragraphs: ['Biblius est un Library OS conçu pour rendre les collections universitaires plus accessibles, structurées et intelligentes.', 'Notre objectif est de réunir catalogue, circulation et ressources numériques dans un même espace.'] },
  contact: { title: 'Contacter Biblius', eyebrow: 'Entreprise', paragraphs: ['Pour toute question, écrivez-nous à contact@biblius.io.', 'Nous pouvons vous accompagner pour la configuration Supabase, les rôles et le déploiement de votre bibliothèque.'] },
  blog: { title: 'Le blog Biblius', eyebrow: 'Entreprise', paragraphs: ['Retrouvez prochainement nos articles sur la gestion documentaire, la classification Dewey et les usages de l’intelligence artificielle en bibliothèque.'] },
  carrieres: { title: 'Carrières', eyebrow: 'Entreprise', paragraphs: ['Biblius construit des outils utiles aux bibliothèques et aux communautés universitaires.', 'Les opportunités seront publiées ici au fil de notre développement.'] },
  confidentialite: { title: 'Politique de confidentialité', eyebrow: 'Informations légales', paragraphs: ['Biblius utilise les données nécessaires à l’authentification, à la gestion du catalogue et au fonctionnement des services demandés.', 'Les clés privées et secrets serveur ne sont jamais exposés dans le navigateur.'] },
  conditions: { title: 'Conditions d’utilisation', eyebrow: 'Informations légales', paragraphs: ['L’utilisation de Biblius doit respecter les règles de votre établissement et les droits associés aux ressources numériques.', 'Les administrateurs sont responsables de la configuration des accès et des rôles.'] },
  'mentions-legales': { title: 'Mentions légales', eyebrow: 'Informations légales', paragraphs: ['Biblius · Library OS · Lyon, France.', 'Contact : contact@biblius.io.'] },
}

export default function FooterPage({ slug }: { slug: string }) {
  const page = content[slug] || content.documentation
  return <main className="min-h-screen bg-slate-50 text-slate-900 dark:bg-slate-950 dark:text-slate-100"><div className="mx-auto max-w-3xl px-6 py-16 lg:px-8"><Link href="/" className="mb-16 inline-flex items-center gap-2 text-sm text-slate-500 hover:text-blue-600 dark:text-slate-400"><ArrowLeft size={16} /> Retour à Biblius</Link><div className="mb-10 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-600 text-white"><Library size={20} /></div><div><strong className="block">Biblius</strong><span className="text-xs text-slate-500 dark:text-slate-400">Library OS · Memory Labs</span></div></div><p className="mb-3 text-xs font-semibold uppercase tracking-[.18em] text-blue-600 dark:text-blue-400">{page.eyebrow}</p><h1 className="mb-8 text-4xl font-bold tracking-tight">{page.title}</h1><div className="space-y-5 text-base leading-8 text-slate-600 dark:text-slate-300">{page.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><footer className="mt-16 border-t border-slate-200 pt-6 text-xs text-slate-500 dark:border-slate-800 dark:text-slate-400">© 2026 Biblius. Conçu pour les bibliothèques universitaires.</footer></div></main>
}
